import {escapeHTML} from './email-html.mjs';

export function renderEmailCatalog(entries){
  const items=entries.map((e,i)=>`<a href="#${e.id}" data-index="${i}"><span>${i+1}.</span> ${escapeHTML(e.title)}</a>`).join('');
  const options=entries.map((e,i)=>`<option value="${i}">${escapeHTML(e.title)}</option>`).join('');
  const data=JSON.stringify(entries).replaceAll('<','\\u003c');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mentorship emails</title><style>
*{box-sizing:border-box}html,body{height:100%;margin:0}body{font:15px/1.45 Arial,sans-serif;color:#0c0c31;background:#f2f3f9;display:grid;grid-template-columns:280px minmax(0,1fr);grid-template-rows:minmax(0,1fr);height:100dvh;overflow:hidden}
aside{min-height:0;background:#fff;border-right:1px solid #dddfea;display:flex;flex-direction:column}h1{font-size:19px;margin:0;padding:22px 18px;border-bottom:1px solid #dddfea}nav{min-height:0;overflow-y:scroll;overscroll-behavior:contain;padding:10px;flex:1}nav a{display:block;padding:11px 10px;margin:2px 0;border-radius:5px;color:inherit;text-decoration:none}nav a span{color:#72758b}nav a:hover{background:#f2f3f9}nav a[aria-current=true]{background:#e9ebff;color:#2630bb;font-weight:bold}a:focus-visible,button:focus-visible,select:focus-visible{outline:3px solid #3d46f2;outline-offset:2px}
main{min-width:0;min-height:0;display:flex;flex-direction:column}header{flex-shrink:0;max-height:48%;overflow-y:auto;background:#fff;padding:20px 28px;border-bottom:1px solid #dddfea}h2{font-size:22px;line-height:1.3;margin:0 0 8px}p{margin:4px 0;color:#555b71}.controls{display:flex;align-items:center;gap:10px;margin-top:14px}button{font:inherit;background:white;border:1px solid #ccd0df;border-radius:5px;padding:7px 12px;cursor:pointer}button:disabled{opacity:.4;cursor:default}.controls span{font-size:13px;color:#626779}.viewer{flex:1;min-height:0}iframe{display:block;border:0;width:100%;height:100%;background:#f2f3f9}.mobile{display:none}
@media(max-width:700px){body{display:block}aside{display:none}main{height:100%}header{padding:14px 16px}h2{font-size:19px}.mobile{display:block;width:100%;font:inherit;margin:0 0 14px;padding:8px}.controls{margin-top:10px}}
.viewer{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1px;background:#dddfea;overflow:hidden}.panel{min-width:0;min-height:0;display:flex;flex-direction:column;background:#f2f3f9}.panel-heading{padding:14px 20px;background:#fff;border-bottom:1px solid #dddfea}.panel h3{font-size:17px;margin:0 0 6px}.panel-heading p{font-size:14px;overflow-wrap:anywhere}.panel iframe{flex:1;min-height:0}.panel-heading strong{color:#0c0c31}
@media(max-width:1100px){.viewer{display:block;overflow-y:auto}.panel{min-height:0}.panel iframe{flex:none;height:65vh}.panel+.panel{border-top:1px solid #dddfea}}
</style></head><body><aside><h1>Email previews</h1><nav aria-label="Choose an email">${items}</nav></aside><main><header><select class="mobile" aria-label="Choose an email">${options}</select><h2 id="subject"></h2><p id="recipient"></p><p><strong>Sent when:</strong> <span id="trigger"></span></p><p><strong>If they reply:</strong> <span id="reply"></span></p><div class="controls"><button id="previous" type="button">Previous</button><button id="next" type="button">Next</button><span id="position" aria-live="polite"></span></div></header><div class="viewer"><section class="panel" aria-labelledby="template-label"><div class="panel-heading"><h3 id="template-label">Template with variables</h3><p><strong>Subject:</strong> <span id="template-subject"></span></p><p>Braces such as {{mentor_name}} show what gets inserted.</p></div><iframe name="email-viewer" title="Email template" sandbox></iframe></section><section class="panel" aria-labelledby="example-label"><div class="panel-heading"><h3 id="example-label">Finished example</h3><p><strong>Subject:</strong> <span id="example-subject"></span></p><p id="example-note"></p></div><iframe name="example-viewer" title="Finished fictional email" sandbox></iframe></section></div></main>
<script>const emails=${data};const frame=document.querySelector('[name="email-viewer"]'),exampleFrame=document.querySelector('[name="example-viewer"]'),select=document.querySelector('select'),previous=document.getElementById('previous'),next=document.getElementById('next');let index=0;
function show(chosen){index=Math.max(0,Math.min(emails.length-1,chosen));const email=emails[index];document.getElementById('subject').textContent=email.title;document.getElementById('template-subject').textContent=email.subject;document.getElementById('example-subject').textContent=email.exampleSubject;document.getElementById('example-note').textContent=email.exampleNote;document.getElementById('recipient').textContent='To: '+email.recipient;document.getElementById('trigger').textContent=email.trigger;document.getElementById('reply').textContent=email.reply;document.getElementById('position').textContent=(index+1)+' of '+emails.length;frame.title=email.title+' template';exampleFrame.title=email.title+' finished example';if(frame.getAttribute('src')!==email.id+'.html'){frame.src=email.id+'.html';exampleFrame.srcdoc=email.exampleHTML;}select.value=String(index);document.querySelectorAll('nav a').forEach((a,i)=>{if(i===index)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current')});previous.disabled=index===0;next.disabled=index===emails.length-1;}
const nav=document.querySelector('nav');let scrollFrame=0,saveTimer=0;
function savePosition(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{history.replaceState(null,'','#'+emails[index].id);}catch{/* Local-file history restrictions must not interrupt the viewer. */}},180);}
nav.addEventListener('scroll',()=>{if(scrollFrame)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=0;const range=nav.scrollHeight-nav.clientHeight;if(range<=0)return;const chosen=Math.max(0,Math.min(emails.length-1,Math.round(nav.scrollTop/range*(emails.length-1))));if(chosen!==index){show(chosen);savePosition();}});},{passive:true});
function choose(i){show(i);savePosition();}nav.addEventListener('click',event=>{const link=event.target.closest('a[data-index]');if(!link)return;event.preventDefault();choose(Number(link.dataset.index));});select.addEventListener('change',()=>choose(Number(select.value)));previous.addEventListener('click',()=>choose(index-1));next.addEventListener('click',()=>choose(index+1));function restore(){show(Math.max(0,emails.findIndex(e=>e.id===location.hash.slice(1))));}window.addEventListener('hashchange',restore);restore();</script></body></html>`;
}
